# Generated by Django 6.0.3 on 2026-03-09 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_alter_deliverable_options'),
        ('reports', '0002_report_monthly_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchTermSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of the month')),
                ('source', models.CharField(choices=[('gbp', 'Google Business Profile'), ('gsc', 'Google Search Console'), ('brightlocal', 'BrightLocal'), ('ahrefs', 'Ahrefs')], max_length=15)),
                ('keyword', models.CharField(max_length=300)),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('avg_position', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('local_pack', models.BooleanField(default=False, help_text='Appears in Local Pack?')),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_terms', to='clients.project')),
            ],
            options={
                'verbose_name': 'Search Term Snapshot',
                'ordering': ['-month', '-impressions'],
            },
        ),
        migrations.CreateModel(
            name='GA4Metrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of the month')),
                ('active_users', models.IntegerField(default=0)),
                ('new_users', models.IntegerField(default=0)),
                ('total_sessions', models.IntegerField(default=0)),
                ('avg_engagement_time_sec', models.IntegerField(default=0, help_text='Average engagement time in seconds')),
                ('total_events', models.IntegerField(default=0)),
                ('page_views', models.IntegerField(default=0)),
                ('scrolls', models.IntegerField(default=0)),
                ('phone_clicks', models.IntegerField(default=0)),
                ('estimate_requests', models.IntegerField(default=0)),
                ('whatsapp_clicks', models.IntegerField(default=0)),
                ('email_clicks', models.IntegerField(default=0)),
                ('direction_clicks', models.IntegerField(default=0)),
                ('high_intent_pages', models.IntegerField(default=0)),
                ('financing_interest', models.IntegerField(default=0)),
                ('traffic_sources', models.JSONField(blank=True, default=list, help_text='Top traffic sources with sessions and key events')),
                ('country_breakdown', models.JSONField(blank=True, default=list)),
                ('top_pages', models.JSONField(blank=True, default=list)),
                ('page_speed', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ga4_metrics', to='clients.project')),
            ],
            options={
                'verbose_name': 'GA4 Metrics',
                'verbose_name_plural': 'GA4 Metrics',
                'ordering': ['-month'],
                'unique_together': {('project', 'month')},
            },
        ),
        migrations.CreateModel(
            name='GBPMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of the month')),
                ('calls', models.IntegerField(default=0)),
                ('chat_clicks', models.IntegerField(default=0)),
                ('bookings', models.IntegerField(default=0)),
                ('direction_clicks', models.IntegerField(default=0)),
                ('website_clicks', models.IntegerField(default=0)),
                ('total_interactions', models.IntegerField(default=0)),
                ('interactions_change_pct', models.DecimalField(blank=True, decimal_places=1, help_text='% change vs comparison period', max_digits=8, null=True)),
                ('profile_views', models.IntegerField(default=0)),
                ('profile_views_change_pct', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True)),
                ('search_desktop_pct', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('search_mobile_pct', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('maps_desktop_pct', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('maps_mobile_pct', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('photo_count', models.IntegerField(default=0)),
                ('review_count', models.IntegerField(default=0)),
                ('review_avg_rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('new_reviews', models.IntegerField(default=0)),
                ('posts_published', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gbp_metrics', to='clients.project')),
            ],
            options={
                'verbose_name': 'GBP Metrics',
                'verbose_name_plural': 'GBP Metrics',
                'ordering': ['-month'],
                'unique_together': {('project', 'month')},
            },
        ),
    ]
