# Generated by Django 5.1.15 on 2026-04-30 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0019_rename_project_to_business'),
        ('reports', '0003_searchtermsnapshot_ga4metrics_gbpmetrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ga4metrics',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ga4_metrics', to='clients.business'),
        ),
        migrations.AlterField(
            model_name='gbpmetrics',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gbp_metrics', to='clients.business'),
        ),
        migrations.AlterField(
            model_name='report',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='clients.business'),
        ),
        migrations.AlterField(
            model_name='searchtermsnapshot',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_terms', to='clients.business'),
        ),
    ]
