# Generated by Django 5.1.15 on 2026-04-30 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0021_rename_project_businesscatalogitem_business'),
        ('reports', '0004_alter_ga4metrics_project_alter_gbpmetrics_project_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ga4metrics',
            old_name='project',
            new_name='business',
        ),
        migrations.RenameField(
            model_name='gbpmetrics',
            old_name='project',
            new_name='business',
        ),
        migrations.RenameField(
            model_name='searchtermsnapshot',
            old_name='project',
            new_name='business',
        ),
        migrations.AlterUniqueTogether(
            name='ga4metrics',
            unique_together={('business', 'month')},
        ),
        migrations.AlterUniqueTogether(
            name='gbpmetrics',
            unique_together={('business', 'month')},
        ),
    ]
