# Generated by Django 5.1.15 on 2026-05-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_retarget_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='gbpmetrics',
            name='gbp_store_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='gbpmetrics',
            name='maps_desktop_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gbpmetrics',
            name='maps_mobile_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gbpmetrics',
            name='search_desktop_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gbpmetrics',
            name='search_mobile_views',
            field=models.IntegerField(default=0),
        ),
    ]
