# Generated by Django 5.1.15 on 2026-04-30 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0019_rename_project_to_business'),
        ('notifications', '0002_add_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='clients.business'),
        ),
    ]
