# Generated by Django 6.0 on 2025-12-31 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('target_url', models.URLField(blank=True)),
                ('search_volume', models.PositiveIntegerField(blank=True, null=True)),
                ('difficulty', models.PositiveSmallIntegerField(blank=True, help_text='Keyword difficulty 0-100', null=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary vs secondary keyword')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='clients.clientprofile')),
            ],
            options={
                'ordering': ['-is_primary', 'keyword'],
                'unique_together': {('client', 'keyword')},
            },
        ),
        migrations.CreateModel(
            name='KeywordRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(help_text='Ranking position (1-100, 0 = not ranked)')),
                ('recorded_date', models.DateField()),
                ('search_engine', models.CharField(choices=[('google', 'Google'), ('bing', 'Bing'), ('yahoo', 'Yahoo')], default='google', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='keywords.keyword')),
            ],
            options={
                'ordering': ['-recorded_date'],
                'unique_together': {('keyword', 'recorded_date', 'search_engine')},
            },
        ),
    ]
