# Generated by Django 5.1.15 on 2026-04-29 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0018_alter_clientprofile_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(default='#6B7280', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_text', models.CharField(db_index=True, max_length=500)),
                ('status', models.CharField(choices=[('tracked', 'Tracked'), ('discovered', 'Discovered'), ('ignored', 'Ignored'), ('paused', 'Paused')], default='discovered', max_length=20)),
                ('intent', models.CharField(blank=True, choices=[('informational', 'Informational'), ('navigational', 'Navigational'), ('commercial', 'Commercial'), ('transactional', 'Transactional'), ('local', 'Local')], max_length=20)),
                ('group_name', models.CharField(blank=True, max_length=255)),
                ('is_branded', models.BooleanField(default=False)),
                ('is_primary', models.BooleanField(default=False)),
                ('maps_enabled', models.BooleanField(default=False)),
                ('target_url', models.URLField(blank=True, max_length=2048)),
                ('target_rank', models.IntegerField(blank=True, null=True)),
                ('location_code', models.IntegerField(blank=True, null=True)),
                ('location_name', models.CharField(blank=True, max_length=255)),
                ('language_code', models.CharField(blank=True, max_length=10)),
                ('search_volume', models.IntegerField(blank=True, null=True)),
                ('competition', models.FloatField(blank=True, null=True)),
                ('competition_level', models.CharField(blank=True, max_length=20)),
                ('cpc', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('keyword_difficulty', models.IntegerField(blank=True, null=True)),
                ('estimated_traffic', models.FloatField(blank=True, null=True)),
                ('estimated_traffic_cost', models.FloatField(blank=True, null=True)),
                ('current_organic_rank', models.IntegerField(blank=True, null=True)),
                ('current_organic_url', models.URLField(blank=True, max_length=2048)),
                ('current_maps_rank', models.IntegerField(blank=True, null=True)),
                ('previous_organic_rank', models.IntegerField(blank=True, null=True)),
                ('previous_maps_rank', models.IntegerField(blank=True, null=True)),
                ('rank_change', models.IntegerField(blank=True, null=True)),
                ('current_mobile_rank', models.IntegerField(blank=True, null=True)),
                ('previous_mobile_rank', models.IntegerField(blank=True, null=True)),
                ('mobile_rank_change', models.IntegerField(blank=True, null=True)),
                ('current_mobile_url', models.URLField(blank=True, max_length=2048)),
                ('last_checked_at', models.DateField(blank=True, null=True)),
                ('first_discovered_at', models.DateField(blank=True, null=True)),
                ('discovery_rank', models.IntegerField(blank=True, null=True)),
                ('promoted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='clients.project')),
                ('tags', models.ManyToManyField(blank=True, related_name='keywords', to='keywords.keywordtag')),
            ],
            options={
                'ordering': ['keyword_text'],
                'indexes': [models.Index(fields=['project', 'status'], name='keywords_ke_project_6ec518_idx'), models.Index(fields=['project', 'status', '-search_volume'], name='keywords_ke_project_201d18_idx'), models.Index(fields=['project', '-current_organic_rank'], name='keywords_ke_project_472fae_idx')],
                'unique_together': {('project', 'keyword_text', 'location_code')},
            },
        ),
    ]
