# Generated by Django 5.1.15 on 2026-04-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='current_mobile_rank_group',
            field=models.IntegerField(blank=True, help_text='rank_group on mobile (organic-only)', null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='current_organic_rank_group',
            field=models.IntegerField(blank=True, help_text='rank_group (organic-only position)', null=True),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='current_mobile_rank',
            field=models.IntegerField(blank=True, help_text='rank_absolute on mobile', null=True),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='current_organic_rank',
            field=models.IntegerField(blank=True, help_text='rank_absolute (entire SERP page)', null=True),
        ),
    ]
