# Generated by Django 5.1.15 on 2026-04-30 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0021_rename_project_businesscatalogitem_business'),
        ('keywords', '0003_alter_keyword_project'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='keyword',
            name='keywords_ke_project_6ec518_idx',
        ),
        migrations.RemoveIndex(
            model_name='keyword',
            name='keywords_ke_project_201d18_idx',
        ),
        migrations.RemoveIndex(
            model_name='keyword',
            name='keywords_ke_project_472fae_idx',
        ),
        migrations.RenameField(
            model_name='keyword',
            old_name='project',
            new_name='business',
        ),
        migrations.AlterUniqueTogether(
            name='keyword',
            unique_together={('business', 'keyword_text', 'location_code')},
        ),
        migrations.AddIndex(
            model_name='keyword',
            index=models.Index(fields=['business', 'status'], name='keywords_ke_busines_75c07f_idx'),
        ),
        migrations.AddIndex(
            model_name='keyword',
            index=models.Index(fields=['business', 'status', '-search_volume'], name='keywords_ke_busines_52d64d_idx'),
        ),
        migrations.AddIndex(
            model_name='keyword',
            index=models.Index(fields=['business', '-current_organic_rank'], name='keywords_ke_busines_dbff78_idx'),
        ),
    ]
