# Generated by Django 5.1.15 on 2026-04-30 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0019_rename_project_to_business'),
        ('rankings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localfinderresult',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_finder_results', to='clients.business'),
        ),
        migrations.AlterField(
            model_name='mapsrankresult',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maps_results', to='clients.business'),
        ),
        migrations.AlterField(
            model_name='serpresult',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serp_results', to='clients.business'),
        ),
    ]
