# Generated by Django 5.1.15 on 2026-04-30 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0021_rename_project_businesscatalogitem_business'),
        ('keywords', '0004_remove_keyword_keywords_ke_project_6ec518_idx_and_more'),
        ('rankings', '0002_alter_localfinderresult_project_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='localfinderresult',
            name='rankings_lo_project_f180d4_idx',
        ),
        migrations.RemoveIndex(
            model_name='mapsrankresult',
            name='rankings_ma_project_4c5ec0_idx',
        ),
        migrations.RemoveIndex(
            model_name='serpresult',
            name='rankings_se_project_5a9846_idx',
        ),
        migrations.RemoveIndex(
            model_name='serpresult',
            name='rankings_se_project_c119b0_idx',
        ),
        migrations.RenameField(
            model_name='localfinderresult',
            old_name='project',
            new_name='business',
        ),
        migrations.RenameField(
            model_name='mapsrankresult',
            old_name='project',
            new_name='business',
        ),
        migrations.RenameField(
            model_name='serpresult',
            old_name='project',
            new_name='business',
        ),
        migrations.AddIndex(
            model_name='localfinderresult',
            index=models.Index(fields=['business', '-checked_at'], name='rankings_lo_busines_0ef416_idx'),
        ),
        migrations.AddIndex(
            model_name='mapsrankresult',
            index=models.Index(fields=['business', '-checked_at'], name='rankings_ma_busines_4badda_idx'),
        ),
        migrations.AddIndex(
            model_name='serpresult',
            index=models.Index(fields=['business', '-checked_at'], name='rankings_se_busines_cb0643_idx'),
        ),
        migrations.AddIndex(
            model_name='serpresult',
            index=models.Index(fields=['business', 'checked_at', 'is_found'], name='rankings_se_busines_b8ef23_idx'),
        ),
    ]
