# Generated by Django 6.0 on 2026-01-03 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('profile_change', 'Profile Change'), ('business_change', 'Business Information Change'), ('offer', 'Special Offer'), ('payment', 'Payment Update'), ('task', 'Task Update'), ('report', 'New Report')], max_length=20)),
                ('target_audience', models.CharField(choices=[('client', 'Client'), ('admin', 'Admin')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('changed_fields', models.JSONField(blank=True, null=True)),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('offer_details', models.JSONField(blank=True, null=True)),
                ('offer_expires_at', models.DateTimeField(blank=True, null=True)),
                ('offer_accepted', models.BooleanField(blank=True, null=True)),
                ('offer_responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_created', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='clients.clientprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
