# Generated by Django 5.1.15 on 2026-04-29 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0018_alter_clientprofile_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveryRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_date', models.DateField(db_index=True)),
                ('total_keywords_found', models.IntegerField(default=0)),
                ('new_keywords_found', models.IntegerField(default=0)),
                ('keywords_in_top_10', models.IntegerField(default=0)),
                ('keywords_in_top_20', models.IntegerField(default=0)),
                ('keywords_in_top_100', models.IntegerField(default=0)),
                ('avg_position', models.FloatField(blank=True, null=True)),
                ('total_estimated_traffic', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('dataforseo_task_id', models.CharField(blank=True, max_length=255)),
                ('dataforseo_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discovery_runs', to='clients.project')),
            ],
            options={
                'ordering': ['-run_date'],
                'unique_together': {('project', 'run_date')},
            },
        ),
        migrations.CreateModel(
            name='DiscoveryResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_text', models.CharField(db_index=True, max_length=500)),
                ('rank_absolute', models.IntegerField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=2048)),
                ('search_volume', models.IntegerField(blank=True, null=True)),
                ('competition', models.FloatField(blank=True, null=True)),
                ('competition_level', models.CharField(blank=True, max_length=20)),
                ('cpc', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('estimated_traffic', models.FloatField(blank=True, null=True)),
                ('keyword_difficulty', models.IntegerField(blank=True, null=True)),
                ('monthly_searches', models.JSONField(blank=True, null=True)),
                ('source', models.CharField(choices=[('ranked', 'Already Ranking'), ('competitor_gap', 'Competitor Gap')], default='ranked', max_length=20)),
                ('competitor_domain', models.CharField(blank=True, max_length=255)),
                ('is_new', models.BooleanField(default=False)),
                ('is_promoted', models.BooleanField(default=False)),
                ('is_interesting', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discovery_results', to='clients.project')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='discovery.discoveryrun')),
            ],
            options={
                'ordering': ['-search_volume'],
                'indexes': [models.Index(fields=['project', '-search_volume'], name='discovery_d_project_418458_idx'), models.Index(fields=['project', 'keyword_text'], name='discovery_d_project_55e087_idx'), models.Index(fields=['run', 'is_new'], name='discovery_d_run_id_4ae4bf_idx')],
            },
        ),
    ]
