# Generated by Django 5.1.15 on 2026-04-30 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0021_rename_project_businesscatalogitem_business'),
        ('discovery', '0002_alter_discoveryresult_project_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='discoveryresult',
            name='discovery_d_project_418458_idx',
        ),
        migrations.RemoveIndex(
            model_name='discoveryresult',
            name='discovery_d_project_55e087_idx',
        ),
        migrations.RenameField(
            model_name='discoveryresult',
            old_name='project',
            new_name='business',
        ),
        migrations.RenameField(
            model_name='discoveryrun',
            old_name='project',
            new_name='business',
        ),
        migrations.AlterUniqueTogether(
            name='discoveryrun',
            unique_together={('business', 'run_date')},
        ),
        migrations.AddIndex(
            model_name='discoveryresult',
            index=models.Index(fields=['business', '-search_volume'], name='discovery_d_busines_636456_idx'),
        ),
        migrations.AddIndex(
            model_name='discoveryresult',
            index=models.Index(fields=['business', 'keyword_text'], name='discovery_d_busines_d53cc2_idx'),
        ),
    ]
