# Generated by Django 5.1.15 on 2026-04-29 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0018_alter_clientprofile_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=255)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('is_auto_discovered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seo_competitors', to='clients.project')),
            ],
            options={
                'ordering': ['domain'],
                'unique_together': {('project', 'domain')},
            },
        ),
        migrations.CreateModel(
            name='CompetitorKeywordOverlap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('keyword_text', models.CharField(db_index=True, max_length=500)),
                ('search_volume', models.IntegerField(blank=True, null=True)),
                ('client_rank', models.IntegerField(blank=True, null=True)),
                ('competitor_rank', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overlaps', to='competitors.competitor')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitor_overlaps', to='clients.project')),
            ],
            options={
                'ordering': ['-search_volume'],
                'indexes': [models.Index(fields=['project', 'competitor', '-date'], name='competitors_project_f53e8f_idx')],
            },
        ),
        migrations.CreateModel(
            name='CompetitorSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('shared_keywords', models.IntegerField(default=0)),
                ('competitor_keywords', models.IntegerField(default=0)),
                ('avg_position', models.FloatField(blank=True, null=True)),
                ('estimated_traffic', models.FloatField(blank=True, null=True)),
                ('domain_rank', models.IntegerField(blank=True, null=True)),
                ('backlinks_count', models.IntegerField(blank=True, null=True)),
                ('referring_domains', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='competitors.competitor')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitor_snapshots', to='clients.project')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['project', '-date'], name='competitors_project_e46169_idx')],
                'unique_together': {('competitor', 'date')},
            },
        ),
    ]
