# Generated by Django 5.1.15 on 2026-04-30 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0019_rename_project_to_business'),
        ('competitors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seo_competitors', to='clients.business'),
        ),
        migrations.AlterField(
            model_name='competitorkeywordoverlap',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitor_overlaps', to='clients.business'),
        ),
        migrations.AlterField(
            model_name='competitorsnapshot',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitor_snapshots', to='clients.business'),
        ),
    ]
