# Generated by Django 5.1.15 on 2026-04-30 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0021_rename_project_businesscatalogitem_business'),
        ('competitors', '0002_alter_competitor_project_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='competitorkeywordoverlap',
            name='competitors_project_f53e8f_idx',
        ),
        migrations.RemoveIndex(
            model_name='competitorsnapshot',
            name='competitors_project_e46169_idx',
        ),
        migrations.RenameField(
            model_name='competitor',
            old_name='project',
            new_name='business',
        ),
        migrations.RenameField(
            model_name='competitorkeywordoverlap',
            old_name='project',
            new_name='business',
        ),
        migrations.RenameField(
            model_name='competitorsnapshot',
            old_name='project',
            new_name='business',
        ),
        migrations.AlterUniqueTogether(
            name='competitor',
            unique_together={('business', 'domain')},
        ),
        migrations.AddIndex(
            model_name='competitorkeywordoverlap',
            index=models.Index(fields=['business', 'competitor', '-date'], name='competitors_busines_5256bc_idx'),
        ),
        migrations.AddIndex(
            model_name='competitorsnapshot',
            index=models.Index(fields=['business', '-date'], name='competitors_busines_0a5679_idx'),
        ),
    ]
