# Generated by Django 5.1.15 on 2026-05-03 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitors', '0003_remove_competitorkeywordoverlap_competitors_project_f53e8f_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='competitorkeywordoverlap',
            unique_together={('competitor', 'date', 'keyword_text')},
        ),
    ]
