# Generated by Django 6.0.3 on 2026-03-07 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectservice',
            name='monthly_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly retainer price', max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='MonthlyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of the month (e.g. 2026-03-01)')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='planned', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_plans', to='clients.projectservice')),
            ],
            options={
                'ordering': ['-month'],
                'unique_together': {('project_service', 'month')},
            },
        ),
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('gbp_post', 'GBP Post'), ('blog_post', 'Blog Post'), ('citation', 'Citation'), ('backlink', 'Backlink'), ('on_page', 'On-Page SEO'), ('technical', 'Technical SEO'), ('review', 'Review Management'), ('reporting', 'Reporting'), ('social', 'Social Media'), ('design', 'Design'), ('development', 'Development'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('link', models.URLField(blank=True, help_text='Live URL, Google Drive link, etc.')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_deliverables', to=settings.AUTH_USER_MODEL)),
                ('monthly_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='clients.monthlyplan')),
            ],
            options={
                'ordering': ['category', 'due_date'],
            },
        ),
    ]
