# Generated by Django 6.0.3 on 2026-03-07 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_projectservice_monthly_price_monthlyplan_deliverable'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. "Premium Local SEO", "Launch Package"', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='deliverable',
            options={'ordering': ['sort_order', 'category', 'due_date']},
        ),
        migrations.AddField(
            model_name='deliverable',
            name='frequency',
            field=models.CharField(choices=[('once', 'Once'), ('weekly', 'Weekly'), ('bi_weekly', 'Bi-Weekly'), ('monthly', 'Monthly'), ('ongoing', 'Ongoing'), ('daily', 'Daily'), ('as_needed', 'As Needed')], default='once', max_length=15),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='live_url',
            field=models.URLField(blank=True, help_text='Published / live URL'),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='target_keyword',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='deliverable',
            name='category',
            field=models.CharField(choices=[('audit', 'Audit'), ('gbp_post', 'GBP Post'), ('gbp_setup', 'GBP Setup'), ('blog_post', 'Blog Post'), ('content', 'Content'), ('citation', 'Citation'), ('backlink', 'Backlink'), ('on_page', 'On-Page SEO'), ('technical', 'Technical SEO'), ('aeo', 'AEO'), ('review', 'Review Management'), ('reporting', 'Reporting'), ('social', 'Social Media'), ('design', 'Design'), ('development', 'Development'), ('logo', 'Logo'), ('branding', 'Branding'), ('ads', 'Google Ads'), ('leads', 'Lead Platforms'), ('competitor', 'Competitor Analysis'), ('account', 'Account Management'), ('qa', 'QA'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='deliverable',
            name='description',
            field=models.TextField(blank=True, help_text='Details / specs'),
        ),
        migrations.AlterField(
            model_name='deliverable',
            name='link',
            field=models.URLField(blank=True, help_text='Draft / Google Drive link'),
        ),
        migrations.AlterField(
            model_name='deliverable',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('scheduled', 'Scheduled'), ('published', 'Published')], default='not_started', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectservice',
            name='monthly_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='MonthlyMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gbp_views', models.IntegerField(blank=True, null=True)),
                ('gbp_searches', models.IntegerField(blank=True, null=True)),
                ('gbp_calls', models.IntegerField(blank=True, null=True)),
                ('gbp_direction_requests', models.IntegerField(blank=True, null=True)),
                ('gbp_website_clicks', models.IntegerField(blank=True, null=True)),
                ('organic_sessions', models.IntegerField(blank=True, null=True)),
                ('organic_conversions', models.IntegerField(blank=True, null=True)),
                ('keywords_top_3', models.IntegerField(blank=True, null=True)),
                ('keywords_top_10', models.IntegerField(blank=True, null=True)),
                ('keywords_local_pack', models.IntegerField(blank=True, null=True)),
                ('total_reviews', models.IntegerField(blank=True, null=True)),
                ('average_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('new_backlinks', models.IntegerField(blank=True, null=True)),
                ('domain_authority', models.IntegerField(blank=True, null=True)),
                ('monthly_retainer', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('content_writer_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tool_costs', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('link_building_spend', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('other_costs', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monthly_plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='clients.monthlyplan')),
            ],
            options={
                'verbose_name_plural': 'Monthly metrics',
            },
        ),
        migrations.CreateModel(
            name='TemplateDeliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('audit', 'Audit'), ('gbp_post', 'GBP Post'), ('gbp_setup', 'GBP Setup'), ('blog_post', 'Blog Post'), ('content', 'Content'), ('citation', 'Citation'), ('backlink', 'Backlink'), ('on_page', 'On-Page SEO'), ('technical', 'Technical SEO'), ('aeo', 'AEO'), ('review', 'Review Management'), ('reporting', 'Reporting'), ('social', 'Social Media'), ('design', 'Design'), ('development', 'Development'), ('logo', 'Logo'), ('branding', 'Branding'), ('ads', 'Google Ads'), ('leads', 'Lead Platforms'), ('competitor', 'Competitor Analysis'), ('account', 'Account Management'), ('qa', 'QA'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('frequency', models.CharField(choices=[('once', 'Once'), ('weekly', 'Weekly'), ('bi_weekly', 'Bi-Weekly'), ('monthly', 'Monthly'), ('ongoing', 'Ongoing'), ('daily', 'Daily'), ('as_needed', 'As Needed')], default='once', max_length=15)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('week_due', models.CharField(blank=True, help_text='e.g. "Week 1", "Week 2", "Ongoing"', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='clients.servicetemplate')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
    ]
