# Generated by Django 6.0.3 on 2026-03-07 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_servicetemplate_alter_deliverable_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverable',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='business_address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='project',
            name='business_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='project',
            name='business_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(help_text='e.g. "904 Dumpster", "Prenga Construction"', max_length=200),
        ),
    ]
