# Generated by Django 6.0.3 on 2026-03-08 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_deliverable_start_date_project_business_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='business_hours',
            field=models.TextField(blank=True, help_text='e.g. "Mon-Fri 8AM-6PM, Sat 9AM-2PM"'),
        ),
        migrations.AddField(
            model_name='project',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='google_business_url',
            field=models.URLField(blank=True, help_text='GBP listing URL'),
        ),
        migrations.AddField(
            model_name='project',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='service_areas',
            field=models.JSONField(blank=True, default=list, help_text='["Jacksonville FL", "Orange Park FL"]'),
        ),
        migrations.CreateModel(
            name='BusinessCatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('product', 'Product'), ('service', 'Service')], default='service', max_length=10)),
                ('name', models.CharField(help_text='e.g. "10 Yard Dumpster", "Interior Painting"', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_unit', models.CharField(blank=True, help_text='e.g. "per rental", "per sqft", "per month", "flat rate"', max_length=50)),
                ('duration_days', models.PositiveIntegerField(blank=True, help_text='Rental/service duration in days', null=True)),
                ('specifications', models.JSONField(blank=True, default=dict, help_text='Flexible specs: {"capacity": "2 tons", "dimensions": "12x8x4 ft"}')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog', to='clients.project')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
