# Generated by Django 6.0.3 on 2026-03-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_project_business_hours_project_facebook_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='competitors',
            field=models.JSONField(blank=True, default=list, help_text='[{"name": "Competitor A", "notes": "..."}]'),
        ),
        migrations.AddField(
            model_name='project',
            name='google_drive_url',
            field=models.URLField(blank=True, help_text='Internal Google Drive folder'),
        ),
        migrations.AddField(
            model_name='project',
            name='industry',
            field=models.CharField(blank=True, help_text='e.g. "Waste Management", "Roofing"', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='marketing_channels',
            field=models.JSONField(blank=True, default=list, help_text='["GMB", "Facebook Ads", "Citations"]'),
        ),
        migrations.AddField(
            model_name='project',
            name='nap_status',
            field=models.CharField(blank=True, help_text='e.g. "High", "Cleaning in progress"', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='target_audience',
            field=models.JSONField(blank=True, default=list, help_text='["General Contractors", "Homeowners"]'),
        ),
        migrations.AddField(
            model_name='project',
            name='usps',
            field=models.JSONField(blank=True, default=list, help_text='["Same-day delivery", "Driveway friendly"]'),
        ),
    ]
