# Generated by Django 6.0.3 on 2026-03-09 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_project_competitors_project_google_drive_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverable',
            options={'ordering': ['due_date', 'sort_order']},
        ),
    ]
