# Generated by Django 6.0.3 on 2026-03-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_remove_monthly_metrics_add_financials_to_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_folder_url',
            field=models.URLField(blank=True, help_text='Image assets folder (Google Drive, Dropbox, etc.)'),
        ),
    ]
