# Generated by Django 6.0.3 on 2026-03-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_project_image_folder_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='booking_url',
            field=models.URLField(blank=True, help_text='Booking/estimate request form URL'),
        ),
        migrations.AddField(
            model_name='project',
            name='citations_url',
            field=models.URLField(blank=True, help_text='Live citations spreadsheet link'),
        ),
    ]
