# Generated by Django 6.0.3 on 2026-03-12 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_add_citations_booking_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=220),
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=220),
        ),
    ]
