# Generated by Django 6.0.3 on 2026-03-12 07:28

from django.db import migrations
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    ClientProfile = apps.get_model('clients', 'ClientProfile')
    Project = apps.get_model('clients', 'Project')

    User = apps.get_model('accounts', 'User')
    used_slugs = set()
    for obj in ClientProfile.objects.select_related('user').all():
        user = obj.user
        full_name = f'{user.first_name} {user.last_name}'.strip() or user.username
        base = slugify(full_name) or 'client'
        slug = base
        n = 1
        while slug in used_slugs or ClientProfile.objects.filter(slug=slug).exclude(pk=obj.pk).exists():
            slug = f'{base}-{n}'
            n += 1
        obj.slug = slug
        obj.save(update_fields=['slug'])
        used_slugs.add(slug)

    used_slugs = set()
    for obj in Project.objects.all():
        base = slugify(obj.name) or 'project'
        slug = base
        n = 1
        while slug in used_slugs or Project.objects.filter(slug=slug).exclude(pk=obj.pk).exists():
            slug = f'{base}-{n}'
            n += 1
        obj.slug = slug
        obj.save(update_fields=['slug'])
        used_slugs.add(slug)


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_add_slugs'),
    ]

    operations = [
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
    ]
