# Generated by Django 6.0.3 on 2026-03-12 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_populate_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
    ]
