# Generated by Django 6.0.3 on 2026-03-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_enforce_slug_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverable',
            name='estimated_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Expected time in minutes (e.g. 10 for a GBP post)', null=True),
        ),
        migrations.AddField(
            model_name='templatedeliverable',
            name='estimated_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Expected time in minutes', null=True),
        ),
    ]
