# Generated by Django 6.0.3 on 2026-03-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_add_estimated_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverable',
            name='category',
            field=models.CharField(choices=[('audit', 'Audit'), ('gbp_post', 'GBP Post'), ('gbp_setup', 'GBP Setup'), ('blog_post', 'Blog Post'), ('content', 'Content'), ('citation', 'Citation'), ('backlink', 'Backlink'), ('on_page', 'On-Page SEO'), ('technical', 'Technical SEO'), ('aeo', 'AEO'), ('review', 'Review Management'), ('reporting', 'Reporting'), ('social', 'Social Media'), ('design', 'Design'), ('development', 'Development'), ('logo', 'Logo'), ('branding', 'Branding'), ('ads', 'Google Ads'), ('leads', 'Lead Platforms'), ('keyword_research', 'Keyword Research'), ('competitor', 'Competitor Analysis'), ('account', 'Account Management'), ('qa', 'QA'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='templatedeliverable',
            name='category',
            field=models.CharField(choices=[('audit', 'Audit'), ('gbp_post', 'GBP Post'), ('gbp_setup', 'GBP Setup'), ('blog_post', 'Blog Post'), ('content', 'Content'), ('citation', 'Citation'), ('backlink', 'Backlink'), ('on_page', 'On-Page SEO'), ('technical', 'Technical SEO'), ('aeo', 'AEO'), ('review', 'Review Management'), ('reporting', 'Reporting'), ('social', 'Social Media'), ('design', 'Design'), ('development', 'Development'), ('logo', 'Logo'), ('branding', 'Branding'), ('ads', 'Google Ads'), ('leads', 'Lead Platforms'), ('keyword_research', 'Keyword Research'), ('competitor', 'Competitor Analysis'), ('account', 'Account Management'), ('qa', 'QA'), ('other', 'Other')], max_length=20),
        ),
    ]
