# Generated by Django 5.1.15 on 2026-04-29 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0015_add_keyword_research_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='contract_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='contract_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='country',
            field=models.CharField(blank=True, default='United States', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='discovery_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='domain',
            field=models.CharField(blank=True, db_index=True, help_text='Bare domain for SEO tracking (e.g. "example.com"). Auto-derived from website_url if blank.', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='google_business_name',
            field=models.CharField(blank=True, help_text='Display name on the GBP listing', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='google_cid',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='google_place_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='language_code',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='project',
            name='location_code',
            field=models.IntegerField(default=2840, help_text='DataForSEO location code (2840 = United States)'),
        ),
        migrations.AddField(
            model_name='project',
            name='location_name',
            field=models.CharField(default='United States', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='max_discovery_keywords',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='project',
            name='monthly_budget_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='["plumber", "florida", "high-priority"]'),
        ),
        migrations.AddField(
            model_name='project',
            name='track_maps',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='track_mobile',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='track_organic',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_code', models.IntegerField(db_index=True, unique=True)),
                ('location_name', models.CharField(db_index=True, max_length=500)),
                ('location_type', models.CharField(blank=True, max_length=50)),
                ('country_iso_code', models.CharField(blank=True, db_index=True, max_length=10)),
                ('location_code_parent', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['location_name'],
                'indexes': [models.Index(fields=['country_iso_code', 'location_name'], name='clients_loc_country_6de001_idx')],
            },
        ),
        migrations.CreateModel(
            name='QuarterlyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. "Q2 2026" or "Spring 2026 — Repipe push"', max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('quarter_start', models.DateField(help_text='First day of the quarter')),
                ('quarter_end', models.DateField(help_text='Last day of the quarter')),
                ('goals', models.JSONField(blank=True, default=list, help_text='["Reach 50 ranked keywords", "Get 20 GBP reviews"]')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quarterly_plans', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarterly_plans', to='clients.project')),
            ],
            options={
                'ordering': ['-quarter_start'],
                'unique_together': {('project', 'quarter_start')},
            },
        ),
        migrations.AddField(
            model_name='monthlyplan',
            name='quarterly_plan',
            field=models.ForeignKey(blank=True, help_text='Optional roll-up to a quarterly plan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_plans', to='clients.quarterlyplan'),
        ),
    ]
