# Generated by Django 5.1.15 on 2026-04-29 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0016_project_city_project_contract_end_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
    ]
