# Generated by Django 5.1.15 on 2026-04-29 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0017_alter_project_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientprofile',
            options={'ordering': ['business_name']},
        ),
    ]
