# Generated by Django 5.1.15 on 2026-04-30 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0020_create_project_engagement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businesscatalogitem',
            old_name='project',
            new_name='business',
        ),
    ]
