# Generated by Django 5.1.15 on 2026-05-01 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0023_seed_local_seo_projects'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverable',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_deliverables', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='client_visible',
            field=models.BooleanField(default=True, help_text='If False, the client never sees this deliverable regardless of approval.'),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='kind',
            field=models.CharField(choices=[('work', 'Work'), ('configuration', 'Configuration'), ('metric_collection', 'Metric Collection'), ('crawl_request', 'Crawl Request'), ('report', 'Report')], default='work', max_length=20),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='requires_approval',
            field=models.BooleanField(default=False, help_text='If True, a supervisor must approve before the client sees this.'),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_deliverables', to=settings.AUTH_USER_MODEL),
        ),
    ]
