# Generated by Django 6.0.3 on 2026-03-09 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_monthly_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. "Anthropic API", "Ahrefs", "BrightLocal"', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('one_time', 'One-time')], default='monthly', max_length=10)),
                ('category', models.CharField(blank=True, help_text='e.g. "AI Tools", "SEO Tools", "Link Building"', max_length=100)),
                ('start_date', models.DateField(help_text='When this expense started')),
                ('end_date', models.DateField(blank=True, help_text='Leave blank if ongoing', null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_active', 'name'],
            },
        ),
    ]
