# Generated by Django 6.0.3 on 2026-03-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_exchangerate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('rent', 'Rent'), ('utilities', 'Utilities'), ('groceries', 'Groceries'), ('dining', 'Dining Out'), ('delivery', 'Food Delivery'), ('transport', 'Transport'), ('gym', 'Gym/Fitness'), ('health', 'Health/Medical'), ('entertainment', 'Entertainment'), ('clothing', 'Clothing'), ('subscriptions', 'Subscriptions'), ('education', 'Education'), ('savings', 'Savings/Investment'), ('other', 'Other')], max_length=20)),
                ('description', models.CharField(max_length=300)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='LEK', max_length=5)),
                ('month', models.DateField(help_text='First day of the month this expense applies to')),
                ('is_recurring', models.BooleanField(default=False, help_text='If true, auto-suggested for future months')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-month', 'category'],
            },
        ),
        migrations.CreateModel(
            name='PersonalIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('salary', 'Salary'), ('owners_draw', "Owner's Draw"), ('freelance', 'Freelance'), ('other', 'Other')], max_length=15)),
                ('description', models.CharField(help_text='e.g. "Quanta Core salary", "WebWise monthly draw"', max_length=300)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='LEK', max_length=5)),
                ('month', models.DateField(help_text='First day of the month this income applies to')),
                ('is_recurring', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-month', 'source'],
            },
        ),
    ]
