# Generated by Django 6.0.3 on 2026-03-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_add_personal_finance'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalexpense',
            name='is_planned',
            field=models.BooleanField(default=False, help_text='Planned expense for future months'),
        ),
        migrations.AddField(
            model_name='personalincome',
            name='is_planned',
            field=models.BooleanField(default=False, help_text='Planned income for future months'),
        ),
        migrations.AddField(
            model_name='projectcost',
            name='is_planned',
            field=models.BooleanField(default=False, help_text='Planned cost for future months'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('upcoming', 'Upcoming'), ('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='upcoming', max_length=15),
        ),
    ]
