# Generated by Django 6.0.3 on 2026-03-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_personalexpense_is_planned_personalincome_is_planned_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalexpense',
            name='is_planned',
        ),
        migrations.RemoveField(
            model_name='personalincome',
            name='is_planned',
        ),
        migrations.RemoveField(
            model_name='projectcost',
            name='is_planned',
        ),
        migrations.AddField(
            model_name='personalexpense',
            name='planned_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Budgeted/planned amount', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='personalincome',
            name='planned_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Budgeted/planned amount', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='projectcost',
            name='planned_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Budgeted/planned amount', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='personalexpense',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual/paid amount', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='personalincome',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual/received amount', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='projectcost',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual/done amount', max_digits=10, null=True),
        ),
    ]
