# Generated by Django 6.0.3 on 2026-03-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_remove_personalexpense_is_planned_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalexpense',
            options={'ordering': ['-month', 'date', 'category']},
        ),
        migrations.AlterModelOptions(
            name='personalincome',
            options={'ordering': ['-month', 'date', 'source']},
        ),
        migrations.AddField(
            model_name='personalexpense',
            name='date',
            field=models.DateField(blank=True, help_text='Specific date of this expense (e.g. 7th for rent)', null=True),
        ),
        migrations.AddField(
            model_name='personalexpense',
            name='recurring_day',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Day of month for recurring items (e.g. 7 = 7th)', null=True),
        ),
        migrations.AddField(
            model_name='personalincome',
            name='date',
            field=models.DateField(blank=True, help_text='Specific date of this income (e.g. 5th of the month)', null=True),
        ),
        migrations.AddField(
            model_name='personalincome',
            name='recurring_day',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Day of month for recurring items (e.g. 5 = 5th)', null=True),
        ),
    ]
