# Generated by Django 6.0.3 on 2026-03-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_add_date_recurring_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalexpense',
            name='category',
            field=models.CharField(choices=[('rent', 'Rent'), ('utilities', 'Utilities'), ('groceries', 'Groceries'), ('dining', 'Dining Out'), ('delivery', 'Food Delivery'), ('transport', 'Transport'), ('gym', 'Gym/Fitness'), ('health', 'Health/Medical'), ('entertainment', 'Entertainment'), ('clothing', 'Clothing'), ('subscriptions', 'Subscriptions'), ('education', 'Education'), ('savings', 'Savings/Investment'), ('debt', 'Debt'), ('personal', 'Personal'), ('home', 'Home'), ('gifts', 'Gifts'), ('pets', 'Pets'), ('travel', 'Travel'), ('other', 'Other')], max_length=20),
        ),
    ]
