# Generated by Django 5.1.15 on 2026-04-30 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0019_rename_project_to_business'),
        ('payments', '0009_add_expense_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcost',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='clients.business'),
        ),
    ]
