# Generated by Django 6.0.3 on 2026-03-09 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_project_competitors_project_google_drive_url_and_more'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklog',
            name='deliverable',
            field=models.ForeignKey(blank=True, help_text='Link to a deliverable. If null, this is extra/unplanned work.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_logs', to='clients.deliverable'),
        ),
        migrations.AddField(
            model_name='tasklog',
            name='document_link',
            field=models.URLField(blank=True, help_text='Google Drive / draft link'),
        ),
        migrations.AddField(
            model_name='tasklog',
            name='live_link',
            field=models.URLField(blank=True, help_text='Published / live URL'),
        ),
    ]
