# Generated by Django 5.1.15 on 2026-04-29 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_tasklog_deliverable_tasklog_document_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='category',
            field=models.CharField(choices=[('supervisor', 'Supervisor'), ('on_page', 'On-Page SEO'), ('off_page', 'Off-Page SEO'), ('social_media', 'Social Media'), ('technical_seo', 'Technical SEO'), ('ads', 'Ads Expert'), ('content', 'Content / Copywriter'), ('design', 'Designer'), ('development', 'Developer'), ('general_assistant', 'General Assistant')], default='general_assistant', help_text='Specialization. Supervisor has elevated permissions across the app.', max_length=20),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive employees are hidden from assignment pickers.'),
        ),
    ]
