# Generated by Django 5.1.15 on 2026-04-29 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employeeprofile_category_employeeprofile_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeprofile',
            options={'ordering': ['user__first_name', 'user__last_name']},
        ),
    ]
