# Generated by Django 5.1.15 on 2026-04-30 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employeeprofile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='category',
            field=models.CharField(choices=[('supervisor', 'Supervisor'), ('economist', 'Economist'), ('on_page', 'On-Page SEO'), ('off_page', 'Off-Page SEO'), ('social_media', 'Social Media'), ('technical_seo', 'Technical SEO'), ('ads', 'Ads Expert'), ('content', 'Content / Copywriter'), ('design', 'Designer'), ('development', 'Developer'), ('general_assistant', 'General Assistant')], default='general_assistant', help_text='Specialization. Supervisor has elevated permissions across the app.', max_length=20),
        ),
    ]
