# Generated by Django 6.0 on 2026-01-03 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_type', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('paypal', 'PayPal'), ('ria', 'Ria Money Transfer'), ('moneygram', 'MoneyGram'), ('western_union', 'Western Union'), ('zelle', 'Zelle'), ('venmo', 'Venmo'), ('other', 'Other')], max_length=20)),
                ('name', models.CharField(help_text='Display name for this payment method', max_length=100)),
                ('details', models.TextField(help_text='Payment details (account info, instructions, etc.)')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Admin Payment Method',
                'verbose_name_plural': 'Admin Payment Methods',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='reference_number',
            field=models.CharField(blank=True, help_text='Reference/transaction number provided by client', max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method_used',
            field=models.ForeignKey(blank=True, help_text='The admin payment method client used', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.adminpaymentmethod'),
        ),
    ]
