# Generated by Django 5.1.15 on 2026-04-29 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0018_alter_clientprofile_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitationDirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('url', models.URLField(blank=True, max_length=2048)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('is_key_citation', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Citation directories',
                'ordering': ['-is_key_citation', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('found', 'Found'), ('not_found', 'Not Found'), ('claimed', 'Claimed'), ('unclaimed', 'Unclaimed')], default='not_found', max_length=20)),
                ('listing_url', models.URLField(blank=True, max_length=2048)),
                ('listed_name', models.CharField(blank=True, max_length=500)),
                ('listed_address', models.TextField(blank=True)),
                ('listed_phone', models.CharField(blank=True, max_length=50)),
                ('listed_zip', models.CharField(blank=True, max_length=20)),
                ('name_accurate', models.BooleanField(null=True)),
                ('address_accurate', models.BooleanField(null=True)),
                ('phone_accurate', models.BooleanField(null=True)),
                ('zip_accurate', models.BooleanField(null=True)),
                ('last_checked_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='clients.project')),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='citations.citationdirectory')),
            ],
            options={
                'ordering': ['directory__name'],
                'indexes': [models.Index(fields=['project', 'status'], name='citations_c_project_8475c8_idx')],
                'unique_together': {('project', 'directory')},
            },
        ),
    ]
